language: python
python:
  - "2.7"
  - "3.4"
install:
  - pip install pipenv
  - pipenv install --dev --ignore-pipfile
script:
  - pipenv run coverage run ./manage.py test --settings=django_recipes.settings.test
after_success:
  - pipenv coveralls
